### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by atiq-cs** [madskristensen/MiniBlog#228] opened 2016-05-14 08:19 UTC
Can you please implement markdown language support for writing blog contents. Thanks.

**Comment by madskristensen** [comment] 2016-05-16 17:01
Dupe of #180

**Closed by madskristensen** 2016-05-16 17:01 UTC

**Comment by atiq-cs** [comment] 2016-05-18 23:44
Oh I see! Sorry about that. You can delete this issue. Thanks.

**Comment by atiq-cs** [comment] 2018-05-31 10:16
Hi, is there an update on this?
